project_id = "pwdjpguxipapoelnnjnl"

[functions.latest-notification]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-feedback-notification]
verify_jwt = false

[functions.send-feedback-reply]
verify_jwt = false
